# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bbd_lt_Cpp <- function(s, a0, b0, lambda1, lambda2, mu2, gamma, A, Bp1, maxdepth, phi, prod_mu2, prod_lambda2, xvec, yvec_minus_s, yvec, lentz_plus_invBk1dBk, inv_Bk1dBk, BidBj, f) {
    invisible(.Call('BirthDeathBirth_bbd_lt_Cpp', PACKAGE = 'BirthDeathBirth', s, a0, b0, lambda1, lambda2, mu2, gamma, A, Bp1, maxdepth, phi, prod_mu2, prod_lambda2, xvec, yvec_minus_s, yvec, lentz_plus_invBk1dBk, inv_Bk1dBk, BidBj, f))
}

bbd_lt_invert_Cpp <- function(t, a0, b0, lambda1, lambda2, mu2, gamma, x, y, A, Bp1, nblocks, tol, computeMode, nThreads, maxdepth) {
    .Call('BirthDeathBirth_bbd_lt_invert_Cpp', PACKAGE = 'BirthDeathBirth', t, a0, b0, lambda1, lambda2, mu2, gamma, x, y, A, Bp1, nblocks, tol, computeMode, nThreads, maxdepth)
}

BidBj_Cpp <- function(Bp1, xvec, yvec, inv_Bk1dBk, BidBj) {
    invisible(.Call('BirthDeathBirth_BidBj_Cpp', PACKAGE = 'BirthDeathBirth', Bp1, xvec, yvec, inv_Bk1dBk, BidBj))
}

Bk1dBk_Cpp <- function(B, xvec, yvec) {
    .Call('BirthDeathBirth_Bk1dBk_Cpp', PACKAGE = 'BirthDeathBirth', B, xvec, yvec)
}

inv_Bk1dBk_Cpp <- function(Bp1, xvec, yvec, inv_Bk1dBk) {
    invisible(.Call('BirthDeathBirth_inv_Bk1dBk_Cpp', PACKAGE = 'BirthDeathBirth', Bp1, xvec, yvec, inv_Bk1dBk))
}

lentz_Cpp <- function(Bp1, xvec, yvec, lentz) {
    invisible(.Call('BirthDeathBirth_lentz_Cpp', PACKAGE = 'BirthDeathBirth', Bp1, xvec, yvec, lentz))
}

lentz_plus_invBk1dBk_Cpp <- function(Bp1, xvec, yvec, inv_Bk1dBk, lentz_plus_invBk1dBk) {
    invisible(.Call('BirthDeathBirth_lentz_plus_invBk1dBk_Cpp', PACKAGE = 'BirthDeathBirth', Bp1, xvec, yvec, inv_Bk1dBk, lentz_plus_invBk1dBk))
}

phi_Cpp <- function(s, a0, b0, lambda2, mu2, A, Bp1, maxdepth, phi, prod_mu2, prod_lambda2, xvec, yvec_minus_s, yvec, lentz_plus_invBk1dBk, inv_Bk1dBk, BidBj) {
    invisible(.Call('BirthDeathBirth_phi_Cpp', PACKAGE = 'BirthDeathBirth', s, a0, b0, lambda2, mu2, A, Bp1, maxdepth, phi, prod_mu2, prod_lambda2, xvec, yvec_minus_s, yvec, lentz_plus_invBk1dBk, inv_Bk1dBk, BidBj))
}

phi_routine_Cpp <- function(B, prod_mu2, prod_lambda2, Bk1dBk, BidBj, lentz) {
    .Call('BirthDeathBirth_phi_routine_Cpp', PACKAGE = 'BirthDeathBirth', B, prod_mu2, prod_lambda2, Bk1dBk, BidBj, lentz)
}

prod_lambda2_Cpp <- function(a, A, Bp1, mat) {
    .Call('BirthDeathBirth_prod_lambda2_Cpp', PACKAGE = 'BirthDeathBirth', a, A, Bp1, mat)
}

prod_mu2_Cpp <- function(a, A, Bp1, mat) {
    .Call('BirthDeathBirth_prod_mu2_Cpp', PACKAGE = 'BirthDeathBirth', a, A, Bp1, mat)
}

prod_vec_Cpp <- function(a, A, Bp1, mat) {
    .Call('BirthDeathBirth_prod_vec_Cpp', PACKAGE = 'BirthDeathBirth', a, A, Bp1, mat)
}

rcpp_hello_world <- function() {
    .Call('BirthDeathBirth_rcpp_hello_world', PACKAGE = 'BirthDeathBirth')
}

